org.gradle.jvmargs=-Xms128m -Xmx1024m

version=3.9.15
buildNumber=a
gitVersion=?
gitBranch=?
docFormat=html5
metlAssembleDir=../metl-assemble
metlUIDir=../metl-ui
githubToken=?
publishJar=false
sourceforgeUser=?
sourceforgePassword=?
jumpmindUser=?
jumpmindPassword=?
signingKey=
signingPassword=
sonatypeUser=
sonatypePassword=

antVersion=1.10.14
log4jVersion=2.22.1
slf4jVersion=2.0.11
springVersion=6.2.18
springBootVersion=3.5.14
groovyVersion=4.0.26
jettyVersion=12.0.34
commonsLangVersion=3.14.0
commonsTextVersion=1.11.0
commonsRngVersion=1.6
commonsDbcpVersion=2.12.0
commonsIoVersion=2.15.1
commonsNetVersion=3.10.0
commonsCollectionsVersion=4.4
httpComponentsVersion=5.5
jaxenVersion=2.0.0
jacksonVersion=2.17.0
jakartaMailVersion=2.0.3
jdomVersion=2.0.6.1
jt400Version=20.0.7
symmetricVersion=3.15.18.1
servletVersion=6.0.0
h2Version=2.2.224
jspVersion=3.1.1
webSocketVersion=2.2.0
jtdsVersion=1.3.1
postgresqlVersion=42.7.3
mockitoVersion=1.9.5
powerMockVersion=1.6.1
swaggerVersion=2.2.22
springdocVersion=2.5.0
kxmlVersion=2.3.0
vaadinVersion=24.3.11
xmlunitVersion=1.6
activeMqVersion=6.1.0
apachePOIVersion=5.2.5
apacheKafkaVersion=3.7.2
awsEncryptionSdkVersion = 3.0.0
awsSdkVersion1 = 1.12.682
awsSdkVersion2 = 2.25.12
bouncycastleVersion = 1.78
