package org.jumpmind.symmetric.is.core.model;

public enum DataType {

    BIT, BOOLEAN,
    TINYINT, SMALLINT, INTEGER, BIGINT,
    FLOAT, REAL, DOUBLE, NUMERIC, DECIMAL,
    CHAR, VARCHAR, LONGVARCHAR, NCHAR, NVARCHAR, LONGNVARCHAR,
    DATE, TIME, TIMESTAMP,
    BINARY, VARBINARY, LONGVARBINARY,
    NULL, OTHER, JAVA_OBJECT, DISTINCT, STRUCT, ARRAY,
    BLOB, CLOB, NCLOB, 
    REF, DATALINK, ROWID, SQLXML
    
}
